branch-defaults:
  default:
    environment: udagram-backend-dev
    group_suffix: null
deploy:
  artifacts: www/Archive.zip
environment-defaults:
  Udagram-api-env:
    branch: null
    repository: null
global:
  application_name: udagram-backend
  branch: null
  default_ec2_keyname: vockey
  default_platform: Node.js 20
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
